### ISSUE TITLE
Landing page for iPhone 4 Landscape

### ISSUE THREAD

**Issue by andhieka** [joeleba/nexbus#1]
<img width="527" alt="screen shot 2015-09-12 at 8 38 31 am" src="https://cloud.githubusercontent.com/assets/6689743/9829087/1e652398-592b-11e5-9fa5-40029e6d319b.png">

It looks weird in the Chrome simulator for iPhone 4 portrait...

**Comment by andhieka** [comment]
basically when the height is not enough, it looks weird.
and when window height <= 298 px, the nexbus logo becomes very tall (not sure why).

**Comment by karen** [comment]
Are we developing for landscape mode too? Because whoever is using our app in landscape mode should try portrait mode... :sweat_smile:

**Comment by joeleba** [comment]
![screen shot 2015-09-12 at 2 21 18 pm](https://cloud.githubusercontent.com/assets/10117525/9830241/9efeb3e2-5959-11e5-9a39-4ec2cb5fa82a.png)
